# Generated by Django 4.2.23 on 2025-08-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='teaching_courses',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='courses.course'),
        ),
    ]
