# Generated by Django 4.2.23 on 2025-08-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_enrolled_courses_profile_teaching_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
