# Generated by Django 4.2.23 on 2025-08-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image for the homepage gallery.', upload_to='homepage_gallery')),
                ('title', models.CharField(help_text='A short, descriptive title for the image.', max_length=100)),
                ('caption', models.TextField(blank=True, help_text='An optional, longer caption for the image.')),
            ],
            options={
                'verbose_name': 'Home Page Image',
                'verbose_name_plural': 'Home Page Images',
            },
        ),
    ]
