# Generated by Django 4.2.23 on 2025-08-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(help_text='Large background image for the hero section.', upload_to='hero_section')),
                ('heading', models.CharField(help_text='The main, large headline.', max_length=200)),
                ('subheading', models.TextField(blank=True, help_text='A smaller line of text below the headline.')),
                ('button_text', models.CharField(default='Learn More', help_text='Text for the call-to-action button.', max_length=50)),
                ('button_link', models.URLField(help_text='The URL the button should link to (e.g., /courses).')),
                ('is_active', models.BooleanField(default=True, help_text='Only one hero section can be active at a time.')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.DeleteModel(
            name='HomePageImage',
        ),
    ]
